// Auto-generated by make — do not edit
let buildVersion = "0.7.11"
let buildCommit = "53e99aa"
let buildBranch = "main"
let buildDate = "2026-04-05 07:32:23 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
