// Auto-generated by make — do not edit
let buildVersion = "0.9.8"
let buildCommit = "7a6e107"
let buildBranch = "feat/cli-arguments-tdd"
let buildDate = "2026-04-10 11:24:07 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
