// Auto-generated by make — do not edit
let buildVersion = "1.3.0"
let buildCommit = "48548bb"
let buildBranch = "main"
let buildDate = "2026-04-25 01:57:09 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
